volumes:
  mongodb_data: { driver: local }

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: on-failure
    labels:
      traefik.enable: true
      traefik.http.routers.rocketchat.rule: Host(localhost)
      traefik.http.routers.rocketchat.tls: true
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
      ####
      traefik.backend: rocketchat
      traefik.frontend.rule=Host: your.domain.tld
      ####
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat
      MONGO_OPLOG_URL: mongodb://mongodb:27017/local
      ROOT_URL: http://localhost:3000
      PORT: 3000
      DEPLOY_METHOD: docker
     # DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
    depends_on:
      - mongodb
    ports:
      - 3000:3000

  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: on-failure
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: true
      ALLOW_EMPTY_PASSWORD: yes